# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('criterion', '0003_auto_20170506_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='criterionscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.Criterion'),
        ),
        migrations.AddField(
            model_name='criterionscore',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='criterionscore',
            unique_together=set([('criterion', 'supplier')]),
        ),
    ]
