# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 21:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_criterions'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='suppliers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
