# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('id',)},
        ),
    ]
