# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0004_auto_20170506_0939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criterionscore',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='criterionscore',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='criterionscore',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='priority',
        ),
        migrations.DeleteModel(
            name='CriterionScore',
        ),
    ]
