# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0005_auto_20170513_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ('id',)},
        ),
    ]
