# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 20:06
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=redactor.fields.RedactorField(default=''),
            preserve_default=False,
        ),
    ]
