# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='show_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
