# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_auto_20170519_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='show_home',
        ),
    ]
